/**
 * GENERATED by scripts/process-images.mjs — do not edit by hand.
 *
 * `alt` is an i18n key under `pages.gallery.alt`, never prose.
 */
export type Shot = {
  name: string;
  alt: string;
  w: number;
  h: number;
};

export const shots: Shot[] = [
  {
    "name": "bmw-serie3",
    "alt": "bmwSerie3",
    "w": 896,
    "h": 1195
  },
  {
    "name": "audi-a5",
    "alt": "audiA5",
    "w": 896,
    "h": 1195
  },
  {
    "name": "mini-jcw",
    "alt": "miniJcw",
    "w": 896,
    "h": 1195
  },
  {
    "name": "golf-front",
    "alt": "golfFront",
    "w": 896,
    "h": 1195
  },
  {
    "name": "seat-exeo",
    "alt": "seatExeo",
    "w": 1200,
    "h": 1600
  },
  {
    "name": "audi-q5",
    "alt": "audiQ5",
    "w": 896,
    "h": 1195
  }
];
