/**
 * GENERATED by scripts/process-images.mjs — do not edit by hand.
 *
 * `alt` is unused by `Work.tsx`, which renders these decoratively
 * (`alt=""`) — kept here anyway as each shot's stable identifying key.
 */
export type Shot = {
  name: string;
  alt: string;
  w: number;
  h: number;
};

export const shots: Shot[] = [
  {
    "name": "bmw-serie5",
    "alt": "bmwSerie5",
    "w": 1087,
    "h": 1447
  },
  {
    "name": "volvo-xc60",
    "alt": "volvoXc60",
    "w": 1087,
    "h": 1447
  },
  {
    "name": "mini-jcw",
    "alt": "miniJcw",
    "w": 1086,
    "h": 1448
  },
  {
    "name": "seat-wagon",
    "alt": "seatWagon",
    "w": 1200,
    "h": 901
  },
  {
    "name": "audi-q5",
    "alt": "audiQ5",
    "w": 1077,
    "h": 1460
  }
];
