/**
 * GENERATED by scripts/process-images.mjs — do not edit by hand.
 *
 * `focus` is the CSS object-position for the slide. It is centred, because
 * the crops are already taken around the car — offsetting again here would
 * move it off-centre a second time.
 */
export type HeroSlide = {
  name: string;
  alt: string;
  focus: string;
  portrait: { w: number; h: number };
  wide: { w: number; h: number };
};

export const heroSlides: HeroSlide[] = [
  {
    "name": "audi-q5",
    "alt": "audiQ5",
    "focus": "50% 50%",
    "portrait": {
      "w": 821,
      "h": 1460
    },
    "wide": {
      "w": 732,
      "h": 412
    }
  },
  {
    "name": "bmw-serie5",
    "alt": "bmwSerie5",
    "focus": "50% 50%",
    "portrait": {
      "w": 619,
      "h": 1100
    },
    "wide": {
      "w": 739,
      "h": 416
    }
  },
  {
    "name": "mini-jcw",
    "alt": "miniJcw",
    "focus": "50% 50%",
    "portrait": {
      "w": 700,
      "h": 1244
    },
    "wide": {
      "w": 738,
      "h": 415
    }
  },
  {
    "name": "volvo-xc60",
    "alt": "volvoXc60",
    "focus": "50% 50%",
    "portrait": {
      "w": 700,
      "h": 1244
    },
    "wide": {
      "w": 739,
      "h": 416
    }
  }
];
