/**
 * GENERATED by scripts/process-images.mjs — do not edit by hand.
 *
 * `focus` is the CSS object-position for the slide. It is centred, because
 * the crops are already taken around the car — offsetting again here would
 * move it off-centre a second time.
 */
export type HeroSlide = {
  name: string;
  alt: string;
  focus: string;
  portrait: { w: number; h: number };
  wide: { w: number; h: number };
};

export const heroSlides: HeroSlide[] = [
  {
    "name": "audi-q5",
    "alt": "audiQ5",
    "focus": "50% 50%",
    "portrait": {
      "w": 672,
      "h": 1195
    },
    "wide": {
      "w": 609,
      "h": 343
    }
  },
  {
    "name": "mini-jcw",
    "alt": "miniJcw",
    "focus": "50% 50%",
    "portrait": {
      "w": 672,
      "h": 1195
    },
    "wide": {
      "w": 609,
      "h": 343
    }
  },
  {
    "name": "golf-front",
    "alt": "golfFront",
    "focus": "50% 50%",
    "portrait": {
      "w": 672,
      "h": 1195
    },
    "wide": {
      "w": 609,
      "h": 343
    }
  },
  {
    "name": "seat-exeo",
    "alt": "seatExeo",
    "focus": "50% 50%",
    "portrait": {
      "w": 1049,
      "h": 1864
    },
    "wide": {
      "w": 1468,
      "h": 826
    }
  }
];
